# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

from myVideoWidget import myVideoWidget


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(890, 435)
        self.centralWidget = QtWidgets.QWidget(mainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_FileSelect = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_FileSelect.sizePolicy().hasHeightForWidth())
        self.btn_FileSelect.setSizePolicy(sizePolicy)
        self.btn_FileSelect.setObjectName("btn_FileSelect")
        self.gridLayout_3.addWidget(self.btn_FileSelect, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 4, 0, 1, 1)
        self.label_frames = QtWidgets.QLabel(self.centralWidget)
        self.label_frames.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_frames.setObjectName("label_frames")
        self.gridLayout_3.addWidget(self.label_frames, 5, 0, 1, 1)
        self.label_Input = QtWidgets.QLabel(self.centralWidget)
        self.label_Input.setObjectName("label_Input")
        self.gridLayout_3.addWidget(self.label_Input, 1, 0, 1, 1)
        self.label_Model = QtWidgets.QLabel(self.centralWidget)
        self.label_Model.setObjectName("label_Model")
        self.gridLayout_3.addWidget(self.label_Model, 3, 0, 1, 1)
        self.gridLayout_3.setRowStretch(0, 3)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_Original = myVideoWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_Original.sizePolicy().hasHeightForWidth())
        self.widget_Original.setSizePolicy(sizePolicy)
        self.widget_Original.setMinimumSize(QtCore.QSize(320, 240))
        self.widget_Original.setObjectName("widget_Original")
        self.gridLayout.addWidget(self.widget_Original, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_Play_Ori = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Play_Ori.sizePolicy().hasHeightForWidth())
        self.btn_Play_Ori.setSizePolicy(sizePolicy)
        self.btn_Play_Ori.setObjectName("btn_Play_Ori")
        self.horizontalLayout.addWidget(self.btn_Play_Ori)
        self.btn_Pause_Ori = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Pause_Ori.sizePolicy().hasHeightForWidth())
        self.btn_Pause_Ori.setSizePolicy(sizePolicy)
        self.btn_Pause_Ori.setObjectName("btn_Pause_Ori")
        self.horizontalLayout.addWidget(self.btn_Pause_Ori)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 7)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 2)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_Result = myVideoWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_Result.sizePolicy().hasHeightForWidth())
        self.widget_Result.setSizePolicy(sizePolicy)
        self.widget_Result.setMinimumSize(QtCore.QSize(320, 240))
        self.widget_Result.setObjectName("widget_Result")
        self.gridLayout_2.addWidget(self.widget_Result, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_Play_Res = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Play_Res.sizePolicy().hasHeightForWidth())
        self.btn_Play_Res.setSizePolicy(sizePolicy)
        self.btn_Play_Res.setObjectName("btn_Play_Res")
        self.horizontalLayout_2.addWidget(self.btn_Play_Res)
        self.btn_Pause_Res = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Pause_Res.sizePolicy().hasHeightForWidth())
        self.btn_Pause_Res.setSizePolicy(sizePolicy)
        self.btn_Pause_Res.setObjectName("btn_Pause_Res")
        self.horizontalLayout_2.addWidget(self.btn_Pause_Res)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 7)
        self.gridLayout_2.setRowStretch(1, 1)
        self.gridLayout_2.setRowStretch(2, 2)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 2, 1, 1)
        self.gridLayout_4.setColumnMinimumWidth(0, 3)
        self.gridLayout_4.setColumnMinimumWidth(1, 3)
        self.gridLayout_4.setColumnMinimumWidth(2, 3)
        self.gridLayout_4.setColumnStretch(0, 3)
        self.gridLayout_4.setColumnStretch(1, 3)
        self.gridLayout_4.setColumnStretch(2, 3)
        mainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 890, 22))
        self.menuBar.setObjectName("menuBar")
        mainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(mainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(mainWindow)
        self.statusBar.setObjectName("statusBar")
        mainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(mainWindow)
        self.btn_FileSelect.clicked.connect(mainWindow.selectFile)
        self.btn_Play_Res.clicked.connect(mainWindow.VideoPlay_Res)
        self.pushButton.clicked.connect(mainWindow.selectModel)
        self.btn_Pause_Res.clicked.connect(mainWindow.VideoPause_Res)
        self.btn_Pause_Ori.clicked.connect(mainWindow.VideoPause_Ori)
        self.btn_Play_Ori.clicked.connect(mainWindow.VideoPlay_Ori)
        self.pushButton_2.clicked.connect(mainWindow.readyToDetect)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "前景检测系统"))
        self.btn_FileSelect.setText(_translate("mainWindow", "选取视频目录"))
        self.pushButton.setText(_translate("mainWindow", "选择模型文件"))
        self.pushButton_2.setText(_translate("mainWindow", "开始检测"))
        self.label_frames.setText(_translate("mainWindow", "视频总帧数："))
        self.label_Input.setText(_translate("mainWindow", "读入文件数量："))
        self.label_Model.setText(_translate("mainWindow", "模型文件名："))
        self.label_2.setText(_translate("mainWindow", "原视频"))
        self.btn_Play_Ori.setText(_translate("mainWindow", "播放"))
        self.btn_Pause_Ori.setText(_translate("mainWindow", "暂停"))
        self.label_3.setText(_translate("mainWindow", "前景目标"))
        self.btn_Play_Res.setText(_translate("mainWindow", "播放"))
        self.btn_Pause_Res.setText(_translate("mainWindow", "暂停"))

